### ISSUE TITLE
/api/v2 base path is missing from requests

### ISSUE THREAD

**Issue by cehoffman** [grezar/go-circleci#13]
This took way too long to debug, but the requests issued by the library for at least the list pipeline action are missing the `/api/v2` base. It would seem that `BasePath` is never actually utilized anywhere to construct the requests so I would assume all resources are failing in the published library.

**Comment by grezar** [comment]
Wow, sorry for my bad. I'll fix it now.

**Comment by grezar** [comment]
@cehoffman 
Thanks for the report. 
I fixed this issue in #14 and released a new version [v0.5.0](https://github.com/grezar/go-circleci/releases/tag/v0.5.0)

FYI:
I added an example for listing pipelines to make sure that the library actually works 😓 
https://github.com/grezar/go-circleci/blob/main/examples/pipeline.go
